[package]
name = "dvm-libra-deps"
version = "0.1.0"
authors = [
    "Alex Koz. <alexanderkozlovskii@wings.ai>",
    "Dm. Yakushev <dmitryyakushev@wings.ai>",
    "Maxim Kurnikov <maximkurnikov@wings.ai>"
    ]
edition = "2018"


[dependencies]
move-lang = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
libra-crypto = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
vm-runtime-types = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
language-e2e-tests = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
vm = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
vm-cache-map = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
vm-runtime = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
libra-state-view = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
libra-config = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
libra-types = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
move-ir-types = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
stdlib = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
bytecode-verifier = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
lcs = { git = "https://github.com/dfinance/libra.git", package = "libra-canonical-serialization", branch = "14.02.2020" }
compiler = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
libra-logger = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
ir-to-bytecode = { git = "https://github.com/dfinance/libra.git", branch = "14.02.2020" }
