name: Build & Push

on: [push]
# on:
#   push:
#     branches:
#       - master
#       - feature-*
#     tags:
#       - v[0-9]+.[0-9]+.[0-9]+
#   pull_request:
#     branches:
#       - master
#       - feature-*
#     tags:
#       - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker-build-own:
    name: '[OWN] Docker Build'
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: '[OwnRegistry] Build and push docker image'
      uses: dfinance/gh-actions@master
      with:
        name: registry.wings.toys/dfinance/dvm
        username: ${{ secrets.OWN_REGISTRY_USR }}
        password: ${{ secrets.OWN_REGISTRY_PWD }}
        dockerfile: ./.build/Dockerfile
        registry: registry.wings.toys
        cache: true

  docker-build-dh:
    name: '[DockerHub] Docker Build'
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: '[DockerHub] Build and push docker image'
      uses: dfinance/gh-actions@master
      # if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        name: dfinance/dvm
        username: ${{ secrets.DH_REGISTRY_USR }}
        password: ${{ secrets.DH_REGISTRY_PWD }}
        dockerfile: ./.build/Dockerfile
        cache: true
